// <auto-generated />
using part4.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace part4.Data.Migrations
{
    [DbContext(typeof(StoreContext))]
    [Migration("20201029011522_CreateDatabase")]
    partial class CreateDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9");

            modelBuilder.Entity("part4.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageName")
                        .HasColumnName("ImageFileName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "A small and lightweight PC for basic computing tasks.",
                            ImageName = "mini1.jpg",
                            Name = "The Mini",
                            Price = 599.99m
                        },
                        new
                        {
                            Id = 2,
                            Description = "A Business PC for professional applications.",
                            ImageName = "business1.jpg",
                            Name = "The Business",
                            Price = 799.99m
                        },
                        new
                        {
                            Id = 3,
                            Description = "A PC for playing all of the latest and greatest video games.",
                            ImageName = "gamer1.jpg",
                            Name = "The Gamer",
                            Price = 999.99m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
